ip prefix-list PL-DEFAULT seq 1 deny 0.0.0.0/0
ip prefix-list PL-DEFAULT seq 10 permit 0.0.0.0/0 le 32
route-map RM-IN permit 10
  match ip address prefix-list PL-DEFAULT
route-map RM-OUT permit 10
  set local-preference 200
!
router bgp 65001
  bgp router-id 10.8.0.7
  bgp cluster-id 10.0.0.7
  no bgp default-ipv4-unicast
  neighbor 192.168.1.200 remote-as 65000
  neighbor 192.168.1.200 route-map RM-IN in
  neighbor 192.168.1.200 route-map RM-OUT out
  neighbor 192.168.2.1 remote-as 65001
  neighbor 192.168.2.1 route-map RM-IN in
  neighbor 192.168.2.1 route-map RM-OUT out
  address-family ipv4 unicast
    !network 192.0.2.0/24
    neighbor 192.168.2.1 activate
    neighbor 192.168.1.200 activate
  exit-address-family
  !
  address-family ipv6 unicast
    neighbor 192.168.2.1 activate
    neighbor 192.168.1.200 activate
  exit-address-family
!
